-- Active: 1684012103952@@127.0.0.1@3306
CREATE TABLE posts (
  id TEXT NOT NULL UNIQUE PRIMARY KEY,
  creator_id TEXT NOT NULL,
  content TEXT NOT NULL,
  likes INTEGER DEFAULT(0) NOT NULL,
  dislikes INTEGER DEFAULT(0) NOT NULL,
  created_at TEXT DEFAULT (DATETIME()) NOT NULL,
  updated_at TEXT DEFAULT (DATETIME()) NOT NULL,
  Foreign Key (creator_id) REFERENCES users(id)
);

SELECT * FROM posts;

DROP TABLE posts;